sudo: required #sudo permissions required for travis
language: generic
services:
  - docker

before_install:
  - docker build -t adamalad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adamalad/docker-react npm run test
